name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name: Minify CSS and JS
        run: |
          npx gulp minifyJS
          npx gulp minifyCSS

      - name: Deploy to GitHub Pages
        run: |
          git add dist
          git commit -m "Minified files"
          git push origin main

